const SHOW_ALL_ORDERS = 'SHOW_ALL_ORDERS';
const ORDER_SEARCH_TERM = 'ORDER_SEARCH_TERM';
const FILTER_STATUS = 'FILTER_STATUS';
const VALIDATE_LOT_ON_PLAN = 'VALIDATE_LOT_ON_PLAN';
const SAVE_LOT_ON_PLAN = 'SAVE_LOT_ON_PLAN'

export { SHOW_ALL_ORDERS, ORDER_SEARCH_TERM, FILTER_STATUS, VALIDATE_LOT_ON_PLAN, SAVE_LOT_ON_PLAN }