const FILTER_ORDERS_LIST = 'FILTER_ORDERS_LIST';
const VALIDATE_LOT_ON_PLAN = 'VALIDATE_LOT_ON_PLAN';
const SAVE_LOT_ON_PLAN = 'SAVE_LOT_ON_PLAN'

export { FILTER_ORDERS_LIST, VALIDATE_LOT_ON_PLAN, SAVE_LOT_ON_PLAN }